version: 0.1.0.{build}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

init:
  - git config --global core.autocrlf true

install:
  - git submodule update --init

clone_depth: 1
skip_branch_with_pr: true

image: Visual Studio 2017
platform: Any CPU
configuration: Debug

build_script:
  - ps: .\.build\build.ps1

test: off
deploy: off

for:
  -
    branches:
      only:
        - dev
        - /feature/.*/

  -
    branches:
      only:
        - master

    configuration: Release

    after_build:
      - ps: .\.build\pack.ps1

    artifacts:
      - path: '**\*.nupkg'
        name: nuget_packages