init:
  - git config --global core.autocrlf input

clone_depth: 1

image: Visual Studio 2017
platform: Any CPU
configuration: Debug
build_script:
  - ps: .\.build\build.ps1
test: off
deploy: off

for:
  -
    branches:
      only:
        - dev
        - /feature/.*/

  -
    branches:
      only:
        - master

    configuration: Release
