environment:
  version: 0.1.0
  package_version: $(version)

init:
  - git config --global core.autocrlf true
  - ps: Update-AppveyorBuild -Version "$env:version.$env:APPVEYOR_BUILD_NUMBER"

clone_depth: 1
skip_branch_with_pr: true

install:
  - git submodule update --init --recursive
  - ps: Import-Module .\.build\shared.ps1

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(version)'
  package_version: '$(package_version)'

image: Visual Studio 2017
platform: Any CPU
configuration: Debug

build_script:
  - ps: .\.build\build.ps1

after_build:
  - ps: .\.build\pack.ps1

artifacts:
  - path: '**\*.nupkg'
    name: nuget_packages

test: off

for:
  -
    branches:
      only:
        - dev
        - /feature/.*/

    environment:
      package_version: $(version)-pre-alpha-$(APPVEYOR_BUILD_NUMBER)

  -
    branches:
      only:
        - master

    configuration: Release

    before_build:
      - ps: |
          if(($env:APPVEYOR_REPO_TAG -eq $true) -and ($env:APPVEYOR_REPO_TAG_NAME -ne "v$env:version"))
          {
              $host.SetShouldExit(1)
          }

    deploy:
      provider: NuGet
      server:
      api_key:
        secure: VVUgpN7A/HEhl0JgkEPg4ViNEviMzJDQ2aCJUIhGMQ3pPOpYTrGI+J/45OevSI52
      skip_symbols: false
      symbol_server:
      artifact: nuget_packages
      on:
        appveyor_repo_tag: true
